server:
  applicationConnectors:
    - type: http
      port: 5002
  adminConnectors:
    - type: http
      port: 5003

db:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/marquez
  user: olist
  password: ${POSTGRES_PASSWORD}

migrateOnStartup: true

logging:
  level: WARN
  loggers:
    marquez: INFO
